- include: nginx.yml
- include: elixir.yml
- include: git.yml
- include: postgres.yml
- include: clone.yml


- hosts: [web]
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Start nginx
      service: name=nginx state=started

- hosts: [web]
  remote_user: ubuntu
  tasks:
    - name: Install deps
      shell:
        mix do local.hex --force, local.rebar --force
        chdir=/home/ubuntu/reboop/reboop
      environment:
        MIX_ENV: dev
    - name: Compile server
      shell:
        mix do deps.get, deps.compile, compile
        chdir=/home/ubuntu/reboop/reboop
      environment:
        MIX_ENV: dev
