- include: nginx.yml
- include: elixir.yml
- include: git.yml
- include: postgres.yml
- include: clone.yml


- hosts: [web]
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Start nginx
      service: name=nginx state=restarted

- hosts: [web]
  remote_user: ubuntu
  tasks:
    - name: Install deps
      shell:
        mix do local.hex --force, local.rebar --force
        chdir=/home/ubuntu/reboop/reboop
      environment:
        MIX_ENV: dev
    - name: Compile server
      shell:
        mix do deps.get, deps.compile, compile
        chdir=/home/ubuntu/reboop/reboop
      environment:
        MIX_ENV: dev

- hosts: [web]
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Configure phoenix service
      template: src=templates/upstart.conf.j2 dest=/etc/init/{{server_name}}.conf
    - name: Configure nginx
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/{{server_name}}
